src/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view),
    path('products/',include("products.urls")),
    path('purchases/',include("purchases.urls")), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/purchases/urls.py
from django.urls import path
from . import views

app_name='purchases'
urlpatterns = [
    path("start/",views.purchase_start_view,name='start'),
    path("success/",views.purchase_success_view,name='success'),
    path("stopped/",views.purchase_stopped_view,name='stopped'),
]

src/purchases/models.py
from django.db import models
from django.conf import settings
# Create your models here.


from products.models import Product

class Purchase(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,null=True,on_delete=models.CASCADE)
    completed=models.BooleanField(default=False)
    stripe_price=models.IntegerField(default=0)
    timestamp=models.DateTimeField(auto_now_add=True)
    

src/purchases/views.py
import random
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseBadRequest,HttpResponseRedirect
# Create your views here.

from products.models import Product
from .models import Purchase

def purchase_start_view(request):
    if not request.method=="POST":
        return HttpResponseBadRequest("Only POST requests are allowed")
    if not request.user.is_authenticated:
        return HttpResponseBadRequest("You must be logged in")
    handle=request.POST.get("handle")
    obj=Product.objects.get(handle=handle)
    purchase=Purchase.objects.create(user=request.user,product=obj)
    request.session['purchase_id']=purchase.id
    
    number=random.randint(0,1)
    if number==1:
        # success
        return HttpResponseRedirect('/purchases/success/')
        # return purchase_success_view(request) 
    else:
        # stopped
        return HttpResponseRedirect('/purchases/stopped/')
    # return HttpResponse("You're at the purchase start view.") # goto stripe api

def purchase_success_view(request):
    purchase_id=request.session.get("purchase_id")
    if purchase_id:
        purchase=Purchase.objects.get(id=purchase_id)
        purchase.completed=True
        purchase.save()
    return HttpResponse(f"You're at the purchase complete view.{purchase_id}")

def purchase_stopped_view(request):
    return HttpResponse("You're at the purchase stopped view.")

src/templates/purchases/buy-btn-form.html
{% if product %}
<form method="POST" action="{% url 'purchases:start' %}">{% csrf_token %}
    <input type="hidden" value="{{ product.handle }}" name="handle" />
    <div class="flex items-baseline text-gray-900 dark:text-white">
        <span class="text-3xl font-semibold">$</span>
        <span class="text-5xl font-extrabold tracking-tight">
            {{ product.display_price }}
        </span>
  </div>
  
  <button
  type="submit"
  class="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
  >
  Buy Now
</button>
</div>

</form>
{% endif %}